# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65cd6497ae6dc1b60a627e214e544343188333b016ecf448ae496b05bfe4463df8f8fd0306e221213aa06366c040863a4343db843734f7985cdcb326cf5c26fb

test:
  secret_key_base: a8d2861553fd04a96d5677793f37e64e8ac4d8eaffb6c0cce7423a9a3d692a45c5b811a05674a1d24f48dec5b257d7d625b49fa7dfe9f63cea7c95a0bc490813

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
